### ISSUE TITLE
Provide schematic for coaxial connection

### ISSUE THREAD

**Issue by zonaj** [elehobica/pico_spdif_recorder#4]
The circuit picture shows the pin assignments and connections for a DLR1160 optical RX module, but there is no such thing for a coaxial (RCA female) connector.

**Comment by elehobica** [comment]
Hello. Thanks for the inquiry. For the coax input (or switchable inputs between coax and toslink), could you please refer to https://github.com/elehobica/pico_spdif_rx?

**Comment by zonaj** [comment]
Oh, nice! That is perfect. Thank you!
